general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]
general.working_directory = "/home/santos/ws"


[window]
opacity = 0.75
#decorations = "None"
startup_mode = "Maximized"
title = "noo god please no!"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 12

[terminal]
shell.program = "tmux"

[keyboard]
bindings = [{ key = "F11", mods = "Shift", action = "ToggleFullscreen" }]
